@Api = http://localhost:5217

### Create catalog
POST {{Api}}/graphql/
Content-Type: application/json
Accept: application/json

{
  "query": "mutation ($input: CreateCatalogInput!) { createCatalog(CreateCatalog: $input) { id name description } }",
  "variables": {
    "input": {
      "name": "Your Catalog Name",
      "description": "Your Catalog Description"
    }
  }
}

###
