@Api = http://localhost:5217

### Get catalog and products by catalog id
GRAPHQL {{Api}}/graphql/

query Get($id: ID!) {
  catalogById(id: $id) {
    name
    description
  }
  productsByCatalogId(
    catalogId: $id 
    order: { price:ASC }
    first: 3
    ) {
    nodes {
      id
      name
      description
      price
    }
    pageInfo {
      hasNextPage
    }
  }
}

{
    "id": "Q2F0YWxvZwpnY2U2MmIyOTU3MWRjNDFjZmFmYmUyZGI2OTJiZTBiZDQ="
}